### ISSUE TITLE
Layout Design for "Understanding FOIA" and "About this Project"

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#354]

**Comment by khandelwal** [comment]
In the Understanding FOIA - which of the two options are you recommending? I think it's the non-FAQ version but I want to be sure. 

You mention re-thinking the content. What aspects of the current content do you not like? 

I'm trying to see if we can move this forward enough so that it is implementable.

**Comment by rjmajma** [comment]
One additional question to think about, @vz3 and @ericadeahl: if and how do these designs need to change given Erica's recent design work?

**Comment by jtag** [comment]
@vz3 and @ericadeahl will sync up on solution during implementation.

**Comment by jtag** [comment]
@ericadeahl  Victor and I reviewing this now and realize you need to weigh in on visual treatment of some of these ideas and work with @vz on it.

**Comment by ericadeahl** [comment]
@vz3 @jtag 
Oops, didn't realize there were these new layouts for these pages. Here's what I mocked up - I don't think they're too far off from what you were looking at.

![foia_aboutthisproject](https://cloud.githubusercontent.com/assets/5911280/5685192/d745dee4-97ec-11e4-83d1-630ccde29abb.png)
![foia_understandingfoia](https://cloud.githubusercontent.com/assets/5911280/5685193/db828aca-97ec-11e4-950a-e4fd83a3dd72.png)

**Comment by khandelwal** [comment]
@ericadeahl's comps are the final.
