### ISSUE TITLE
Fix remaining UI glitches

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#430]
Split to #531 #532 #533 #535

**Comment by ericadeahl** [comment]
Hi @vz3 here are my notes. Let me know if you'd like to go through things together. I didn't note anything for "About this Project" since it's in progress.

GLOBAL
- The light font weight looks very light. "Webkit font-smoothing: antialiased" - This seems to be making it thinner. Do we need that?/Should we increase the weight slightly?
- every page should have 60px padding at the bottom (above footer)
- Top nav: make text semibold
- add white bar under header with breadcrumb - on Understanding FOIA, About this Project, Federal Agencies, Agency Detail pages
- Add small search bar in header (except on homepage)

HOME
- reduce padding above and below search bar to 30px
- Add search button and magnifying glass
- Change the small text on this page from 1 em to 1.2em
- “Learn more about FOIA" link: make arrow dark blue to match link
- padding should be 30px between the bottom of text sections and the line below
- padding should be 60px between the line and the top of a new section, and below the last last section

UNDERSTANDING FOIA
- padding at top: 40px
- Change page title to “Understanding FOIA”
- padding under title: 60px
- padding under question link section: 60px
- Add first question title “What is FOIA?"
- remove blue underline from “Why would I make a FOIA request?”
- Add rules 20px under question titles (1px #323A45)
- padding between bottom of text and line: 30px 
- padding between line and next question title: 60px

FEDERAL AGENCIES
- Do you think the title makes sense? Maybe switch to "Find a Federal Agency”? Just thinking about what would make the point of the page clearer...
- eliminate the black search bar section at the top of the page? Alternately, keep the search bar but eliminate the text above and below the box, and reduce the black space to 30px above and below search bar
- Change page title to “Federal Agencies” (or “Find a Federal Agency" or whatever we decide)
- Increase text size of agency titles to 1.2em
- padding at bottom of page: 60px

AGENCY DETAIL
- breadcrumb should be on white background
- reduce breadcrumb text size to .8em
- increase “Submit a Request” text size to 1.5em
- reduce padding between “Submit a Request” and line below to 20px
- increase “Request by Mail” etc title sizes to 1.2em
- in the white box: reduce the size of the icons to 1.5em and move them over to the right slightly so the top and side margins match
- the footer should stick to the bottom of the page. On a large screen I am seeing gray space below the footer

**Comment by vz3** [comment]
Checkmarking this list

**Comment by khandelwal** [comment]
Split this up into multiple issues.

**Comment by ericadeahl** [comment]
@vz3  i made a few updates to the list (comparing it to the live site) and checked off things that are done. i think it would make sense to break these into new issues by section. there are two things we could make into their own issues, and deprioritize: adding a bar with breadcrumb across the site, and adding the small search bar in the header (those seem like discreet things that could come later.) otherwise everything seems like small tweaks. if there are things in there that seem problematic let me know and let's discuss/readjust.

**Comment by vz3** [comment]
Moving existing notes here for archival, tracked in individual issues

GLOBAL
- [ ] The light font weight looks very light. "Webkit font-smoothing: antialiased" - This seems to be making it thinner. Do we need that?/Should we increase the weight slightly?
- [ ] every page should have 60px padding at the bottom (above footer)
- [ ] Top nav: make text semibold
- [ ] add white bar under header with breadcrumb - on Understanding FOIA, About this Project, Federal Agencies, Agency Detail pages
- [ ] Add small search bar in header (except on homepage)

HOME
- [x] reduce padding above and below search bar to 30px
- [ ] Add search button and magnifying glass
- [ ] Change the small text on this page from 1 em to 1.2em
- [ ] “Learn more about FOIA" link: make arrow dark blue to match link
- [ ] padding should be 30px between the bottom of text sections and the line below
- [ ] padding should be 60px between the line and the top of a new section, and below the last last section

UNDERSTANDING FOIA
- [ ] padding at top: 40px
- [x] Change page title to “Understanding FOIA”
- [ ] padding under title: 60px
- [x] padding under question link section: 60px
- [x] Add first question title “What is FOIA?"
- [x] remove blue underline from “Why would I make a FOIA request?”
- [x] Add rules 20px under question titles (1px #323A45)
- [x] padding between bottom of text and line: 30px 
- [x] padding between line and next question title: 60px
- [ ] padding at bottom of page: 60px

FEDERAL AGENCIES
- [ ] Do you think the title makes sense? Maybe switch to "Find a Federal Agency”? Just thinking about what would make the point of the page clearer...
- [ ] title should be H1
- [ ] padding at top: 40px
- [x] eliminate the black search bar section at the top of the page? Alternately, keep the search bar but eliminate the text above and below the box, and reduce the black space to 30px above and below search bar
- [x] Change page title to “Federal Agencies” (or “Find a Federal Agency" or whatever we decide)
- [x] Increase text size of agency titles to 1.2em
- [ ] reduce space between agency name and description text
- [ ] make alphabet text links at the top semibold and increase text size to 1.2em
- [ ] make alphabet section headers semibold, 1.5em, #323A45
- [ ] add rule under alphabet section headers
- [ ] add back to top links
- [ ] add the missing letters of the alphabet and have empty categories (maybe?? seems weird to have the alphabet end at U) 
- [ ] padding at bottom of page: 60px

AGENCY DETAIL
- [ ] breadcrumb should be on white background
- [ ] reduce breadcrumb text size to .8em
- [ ] increase “Submit a Request” text size to 1.5em
- [ ] reduce padding between “Submit a Request” and line below to 20px
- [ ] increase “Request by Mail” etc title sizes to 1.2em
- [ ] in the white box: reduce the size of the icons to 1.5em and move them over to the right slightly so the top and side margins match
- [ ] the footer should stick to the bottom of the page. On a large screen I am seeing gray space below the footer
