### ISSUE TITLE
Standardize levels across project

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#432]
In the yamls we have top-levels and departments, in the api/database we have agencies, sub-agencies and offices, in the front-end it seems that we could have up to 4 tiers. 

Let's figure out how to standardize everything for cleaner reference.

**Comment by khandelwal** [comment]
I think the model's reasonably thought out right now. 
On the API/database we have agencies and offices (and that's fine). It's more FOIA-centric in it's organization.  
In the YAML we have a slightly different representation (because it more closely reflects how the government hierarchy works). I do not think we need to standardize these things - there's nothing particularly wrong with the model we have. 

If we add more layers, we might want to re-think at that time.
