### ISSUE TITLE
When AdBlock Plus is enabled in Chrome, Search Results don't work

### ISSUE THREAD

**Issue by polastre** [18F/foia-hub#448]
If you are using Chrome (in my case 39.0.2171.99) and you have AdBlock Plus enabled (https://adblockplus.org/), typing in the search box and selecting an agency results in nothing happening.  The page doesn't refresh and the agency information does not load.

**Comment by polastre** [comment]
AdBlock is definitely blocking:
- Google Analytics - https://www.google-analytics.com/analytics.js
- https://p.typekit.net/p.gif?s=1&k=tbd8pdb&app=&ht=tk&h=foia.18f.us&f=173.174.5474.5475&a=2078371&sl=551&fl=43&_=1422488171556

**Comment by vz3** [comment]
Not able to replicate. When you say "selecting an agency", do you mean clicking on one of the options in the auto complete? If so, there's a bug where the value in the field clears, but you should be directed to the appropriate result. What happens if you just enter a query and hit enter?

Typekit+Google Analytics block shouldn't result in any problems, but I went ahead and installed AdBlock Plus to attempt to replicate.

**Comment by polastre** [comment]
Working for me on my personal laptop, but this laptop has a different ABP set of filter sources.  I wish I could tell you what the sources were on my work laptop, but alas that's all been wiped.

Good luck.
