### ISSUE TITLE
Need more info from backend for search results

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#464]
Need to be able to cut agencies by letter, and to output the number of results from search.

**Comment by ramirezg** [comment]
We could display the number of search results with a quick change to the template like [this](https://github.com/18F/foia-hub/compare/number_add#diff-0f0883c6328aef6c78b95b1ee5a2e6bcR13) or make a special API endpoint for the search template like [this](https://github.com/18F/foia-hub/compare/alpha) to aggregate by letter. 

I'm not sure if the second is best practice for django. Thoughts?

**Comment by konklone** [comment]
The first seems straight forward enough. :+1:

The second one seems like it needs some reworking, because you have a single method potentially returning different kinds of objects. I think we could separate that into two steps: the method that gets all the agencies (which was what we had), and then a separate method that, when given a full list of agencies, returns you a dict with them mapped by name.

Does that make sense?

**Comment by cmc333333** [comment]
There's also http://jinja.pocoo.org/docs/dev/templates/#groupby -- you could do the whole thing in the template.

**Comment by ramirezg** [comment]
@konklone yep, it makes sense, but unfortunately changing the API to return a dict causes a number of issues later. Using the group by function was odd at first but it works using groupby('name.0') to group by the first letter.

**Comment by ramirezg** [comment]
Solved with 18F/foia-hub/pull/465
