### ISSUE TITLE
Move from local Postgres to an RDS server

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#552]
A preliminary step before #551:

- [x] Create an RDS server in the existing `foia` VPC.
- [ ] Move the app to use it.

This will flush out any possible errors or work we have to do to move from local PG to an RDS-based PG.

**Comment by rjmajma** [comment]
Must be done after #551.

**Comment by khandelwal** [comment]
I was able to setup an RDS instance with my personal RDS, and connect to it and run the application. No application changes were required - which is what everyone said and I didn't believe them. 

Good news. 

Now I'll need to create an RDS instance in the existing VPC for Cloud Foundry.

**Comment by khandelwal** [comment]
I've created an RDS instance in Cloud Foundry. It's a 'staging' instance so that we can try connecting to it, etc. Moving the app to it is simply a case of setting up the write database url in the .env when we deploy to Cloud Foundry. This is ready to be closed.  

@konklone How are we managing that .env file for Cloud Foundry? Is there something else you need me to do.

**Comment by konklone** [comment]
Cloud Foundry (and Heroku) both keep environment variables in their own system, and you set them by running a command like `cf set-env` on each environment variable.

The `.env` file is only used for local development -- in effect, to simulate your app's production environment.
