### ISSUE TITLE
Comprehensive list of requirements for CF

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#589]
https://docs.google.com/a/gsa.gov/document/d/1AQOknp55ONS0bPxFR5mt8GcJDtWvZwk8jr8fgrrXNt0/edit?usp=sharing

**Comment by konklone** [comment]
What does this refer to?

**Comment by khandelwal** [comment]
We're running around setting up things in AWS and Cloud Foundry. I think we should view the things we setup as 'staging' in the sense that we're setting up a staging environment while we figure everything out. 

This issue is supposed to encapsulate all that activity into a single list so that we're ready to push to production. What are all the things we need to create or do, before we can say we're in production?

An example would be: create an S3 bucket for static files with x properties, called y .

**Comment by khandelwal** [comment]
What we have right now is an adhoc process. What we need is a more disciplined approach.

**Comment by konklone** [comment]
`cloudfoundry.md`, in the project root, has lots of notes. @ramirezg started a GDoc based on some of it, and I've updated it. It should go back into this project, either as a replacement to `cloudfoundry.md` or as part of the README.

**Comment by khandelwal** [comment]
Yeah, let's not store that list in a Google Doc. Add the steps into cloudfoundry.md - I don't think we need to hide any of the instructions.
